Miscellaneous updates (#959)
- missing-new-line CI job: ensures all source files end with new line
- logging updates
- add new line to the end of many files
- fix header include ordering is misc places
- transition to use hsa::get_core_table() and hsa::get_amd_ext_table() in various places instead of making copies

[ROCm/rocprofiler-sdk commit: 1e49b437384b0c96fec32fe5bef80c20281bdbea]

diff --git a/.github/workflows/formatting.yml b/.github/workflows/formatting.yml
--- a/.github/workflows/formatting.yml
+++ b/.github/workflows/formatting.yml
@@ -143,3 +143,21 @@ jobs:
         command: review
         pull_number: ${{ github.event.pull_request.number }}
         git_dir: '.'
+
+  missing-new-line:
+    runs-on: ubuntu-22.04
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Find missing new line
+      shell: bash
+      run: |
+        OUTFILE=missing_newline.txt
+        for i in $(find source/lib source/include tests samples cmake -type f | egrep -v '\.bin$'); do VAL=$(tail -c 1 ${i}); if [ -n "${VAL}" ]; then echo "- ${i}" >> ${OUTFILE}; fi; done
+        if [[ -f ${OUTFILE} && $(cat ${OUTFILE} | wc -l) -gt 0 ]]; then
+          echo -e "\nError! Source code missing new line at end of file...\n"
+          echo -e "\nFiles:\n"
+          cat ${OUTFILE}
+          exit 1
+        fi
